config/routes.rb
Lms::Engine.routes.draw do
  resources :loans do
    member do
      get :change_date
      get :table
      post :goto_date
    end
  end
end

app/models/lms/actual_event.rb
module Lms
  class ActualTransaction < ApplicationRecord
    belongs_to :loan
  end
end

app/models/lms/actual_transaction.rb
module Lms
  class ActualTransaction < ApplicationRecord
    PAYMENT = "payment"
    WAIVE = "waive"

    belongs_to :loan
  end
end

app/models/lms/application_record.rb
module Lms
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/lms/expected_payment.rb
module Lms
  class ExpectedPayment < ApplicationRecord
    INITIAL_BALANCE = "initial_balance"

    belongs_to :loan
  end
end

app/models/lms/loan.rb
module Lms
  class Loan < ApplicationRecord
    has_many :actual_transactions
    accepts_nested_attributes_for :actual_transactions

    has_many :payments
    accepts_nested_attributes_for :payments

    EARLY = "early"
    LATE = "late"
    ONTIME = "ontime"

    after_create :initialize_repayment_schedule

    def initialize_repayment_schedule
      payment = expected_payment_per_period

      initial_repayment_schedule = initial_repayment_dates.inject({}) do |hash, date|
        hash[date.to_s] = payment
        hash
      end

      update_attributes(repayment_schedule: initial_repayment_schedule)
    end

    def loan_state
      LoanState.new(self)
    end

    def initial_balance
      expected_payment_per_period * period_count
    end

    def expected_payment_per_period
      @eppp ||= AmortizationCalculator.payment_per_period({
        amount: amount,
        interest: interest,
        period_count: period_count,
      })
    end

    def date_of_balance
      initial_repayment_dates.keys.sort.last
    end

    def initial_balance
      loan_state.initial_balance
    end

    def initial_repayment_dates
      RepaymentDates.new(self).execute
    end

    def date_of_balance
      initial_repayment_dates.sort.last
    end

    def current_date
      loan_state.current_date
    end

    def remaining_balance
      loan_state.remaining_balance
    end

    def remaining_principal
      loan_state.remaining_principal
    end

    def remaining_interest
      loan_state.remaining_interest
    end

    def paid_balance
      loan_state.paid_balance
    end

    def paid_interest
      loan_state.paid_interest
    end

    def paid_principal
      loan_state.paid_principal
    end

    def pay_to_balance
      loan_state.pay_to_balance
    end

    def expected_balance
      loan_state.expected_balance
    end

    def status
      loan_state.status
    end

    def last_transaction_date
      [initial_repayment_dates.last.to_s, actual_transactions.last&.created_at&.to_date.to_s].max
    end
  end
end

app/controllers/lms/application_controller.rb
module Lms
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/lms/loans/actual_events_controller.rb
module Lms
  module Loans
    class ActualTransactionsController < ApplicationController
    end
  end
end

app/controllers/lms/loans_controller.rb
module Lms
  class LoansController < ApplicationController
    before_filter :negate_amount, only: [:update]
    before_filter :assign_note, only: [:update]

    def new
      @loan = Loan.new
    end

    def create
      @loan = Loan.create(loan_params)
      @loan.update_attributes(date_today: @loan.start_date)
      redirect_to loan_path(@loan.id)
    end

    def show
      @loan = Loan.find(params[:id])
      @view = ViewBuilder.new(@loan).execute
    end

    def update
      @loan = Loan.find(params[:id])
      @loan.update_attributes(loan_params)
      redirect_to loan_path(@loan.id)
    end

    def table
      @loan = Loan.find(params[:id])
    end

    def loan_params
      params.require(:loan).permit(
        :period, :amount, :interest, :period_count, :start_date,
        actual_transactions_attributes: [:kind, :amount, :updated_at, :created_at, :note],
      )
    end

    def change_date
      @loan = Loan.find(params[:id])
      @loan.update_attributes(date_today: @loan.date_today + 1.day)
      redirect_to loan_path(@loan.id)
    end

    def negate_amount
      params[:loan][:actual_transactions_attributes]["0"][:amount] =
        -params[:loan][:actual_transactions_attributes]["0"][:amount].to_f
    end

    def assign_note
      params[:loan][:actual_transactions_attributes]["0"][:note] =
        params[:loan][:actual_transactions_attributes]["0"][:kind]
    end

    def goto_date
      loan = Loan.find(params[:id])
      new_date = params[:current_date][:date].to_date


      loan.update_attributes(date_today: new_date)

      if new_date < loan.date_today
        loan.actual_transactions.where("created_at >= ? AND created_at < ?", new_date, loan.date_today + 1.day).destroy_all
      end

      redirect_to loan_path(params[:id])
    end
  end
end

app/views/layouts/lms/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plankbot (✿◠‿◠)</title>
  <%= stylesheet_link_tag    "lms/application", media: "all" %>
  <%= javascript_include_tag "lms/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lms/loans/new.html.erb
<div class="new-loan">
  <%= form_for @loan, url: loans_path, method: :post do |f| %>
    <%= f.label :period %>
    <%= f.select :period, ["monthly", "every_three_days"] %>
    <br>
    <%= f.label :amount %>
    <%= f.number_field :amount %>
    <br>
    <%= f.label :interest %>
    <%= f.text_field :interest %>
    <br>
    <%= f.label :period_count %>
    <%= f.text_field :period_count %>
    <br>
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
    <br>
    <%= f.submit "create loan" %>
  <% end %>
</div>

app/views/lms/loans/show.html.erb
<table class="headings">
  <tr>
    <th class="loan-figures"></th>
    <th></th>
    <th></th>
    <th></th>
    <th class="loan-figures"></th>
    <th class="loan-figures"></th>
    <th class="loan-figures"></th>
  </tr>
  <tr>
    <td class="label">
      Amount:
    </td>
    <td>
      <%= number_with_precision(@loan.amount, precision: 2, delimiter: ',') %>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td class="figure-label label">
      Interest
    </td>
    <td class="figure-label label">
      Principal
    </td>
    <td class="figure-label label">
      Total
    </td>
  </tr>
  <tr>
    <td class="label">
      Interest %:
    </td>
    <td>
      <%= @loan.interest * 100 %> %
    </td>
    <td>
    </td>
    <td class="figure-label label">
      Remaining
    </td>
    <td class="figure-label">
      <%= number_with_precision(@loan.remaining_interest, precision: 2, delimiter: ',') %>
    </td>
    <td class="figure-label">
      <%= number_with_precision(@loan.remaining_principal, precision: 2, delimiter: ',') %>
    </td>
    <td class="figure-label">
      <%= number_with_precision(@loan.remaining_balance, precision: 2, delimiter: ',') %>
    </td>
  </tr>
  <tr>
    <td class="label">
      Periods:
    </td>
    <td>
      <%= @loan.period_count %>
    </td>
    <td></td>
    <td class="figure-label label">Paid</td>
    <td class="figure-label">
      <%= number_with_precision(@loan.paid_interest, precision: 2, delimiter: ',') %>
    </td>
    <td class="figure-label">
      <%= number_with_precision(@loan.paid_principal, precision: 2, delimiter: ',') %>
    </td>
    <td class="figure-label">
      <%= number_with_precision(@loan.paid_balance, precision: 2, delimiter: ',') %>
    </td>
  </tr>
  <tr>
    <td class="label">
      Start Date
    </td>
    <td>
      <%= @loan.start_date.strftime(Lms::DailyInterestMapper::DATE_ID_FORMAT) %>
    </td>
  </tr>
  <tr>
    <td class="label">
      Status:
    </td>
    <td class="<%= @loan.status %>">
      <%= @loan.status %>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td class="figure-label label">
      Pay to balance
    </td>
    <td class="figure-label">
      <%= number_with_precision(@loan.pay_to_balance, precision: 2, delimiter: ',') %> </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td class="figure-label label">
      Date now
    </td>
    <td class="figure-label">
      <%= @loan.date_today %>
    </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td>
    </td>
    <td class="figure-label label">
      <%= link_to "Next Day", change_date_loan_path(@loan.id), { method: :get } %>
    </td>
  </tr>
</table>

<br><br><br>

<table class="loan">
  <tr>
    <th class="date">Date</th>
    <th colspan="3">Charges</th>
    <th colspan="3">Payments</th>
    <th>Notes</th>
  </tr>
  <tr>
    <th></th>
    <th>interest</th><th>principal</th><th>total</th>
    <th>interest</th><th>principal</th><th>total</th>
    <th>Notes</th>
  </tr>
  <% @view[:figures].each do |date, txn| %>
    <tr class="<%= txn[:due] %>">
      <td class="date"><%= txn[:date] %></td>
      <td class="numbers"><%= txn[:ctot_ipd] %></td>
      <td class="numbers"><%= txn[:ctot_ppd] %></td>
      <td class="numbers"><%= txn[:ctot_bpd] %></td>
      <td class="numbers"><%= txn[:ptot_ipd] %></td>
      <td class="numbers"><%= txn[:ptot_ppd] %></td>
      <td class="numbers"><%= txn[:ptot_bpd] %></td>
      <td class="numbers"><%= txn[:note] %></td>
    </tr>
  <% end%>
  <tr class="totals">
    <td>
      Totals
    </td>
    <td>
      <%= @view[:totals][:bipd] %>
    </td>
    <td>
      <%= @view[:totals][:bppd] %>
    </td>
    <td>
      <%= @view[:totals][:bbpd] %>
    </td>
    <td>
      <%= @view[:totals][:aipd] %>
    </td>
    <td>
      <%= @view[:totals][:appd] %>
    </td>
    <td>
      <%= @view[:totals][:abpd] %>
    </td>
    <td>
    </td>
  </tr>
  <tr class="totals">
    <td>
    </td>
    <td colspan="3">
      Remaining
    </td>
    <td colspan="3">
      Paid
    </td>
    <td>
    </td>
  </tr>

</table>

<br><br><br>

<table class="loan">
  <tr>
    <th class="date">Date</th>
    <th>Payments</th>
  </tr>
  <% @loan.actual_transactions.each do |at| %>
    <tr>
      <td class="date"><%= at.created_at.strftime("%Y-%m-%d %H %M") %></td>
      <td><%= at.amount.abs.round(2) %></td>
    </tr>
  <% end %>
</table>

<br><br><br>

<div class="controls">
  <%= form_for @loan do |f| %>
    <%= f.fields_for :actual_transactions, @loan.actual_transactions.new do |f| %>
      <%= f.select :kind, ["payment", "waive"] %>
      <%= f.text_field :amount %>
      <%= f.hidden_field :note, value: @loan.date_today %>
      <%= f.hidden_field :created_at, value: @loan.date_today %>
      <%= f.hidden_field :updated_at, value: @loan.date_today %>
    <% end %>
    <%= f.submit "Confirm" %>
  <% end %>

  <%= form_for :current_date, url: goto_date_loan_path(@loan.id) do |form| %>
    <%= form.date_field :date, "data-provide" => 'datepicker' %>
    <%= form.submit "Go to date" %>
  <% end  %>
</div>

app/views/lms/loans/table.html.erb
<table class="loan">
  <tr>
    <th>date</th>
    <th>aaa_bal</th>
    <th>aaa_pri</th>
    <th>day_int</th>
    <th>tot_int</th>
    <th>tot_chg</th>
    <th>int_chg</th>
    <th>pri_chg</th>
    <th>tot_ipd</th>
    <th>tot_ppd</th>
    <th>tot_bpd</th>
    <th>zzz_int</th>
    <th>zzz_pri</th>
    <th>zzz_bal</th>
  </tr>
  <% @loan.loan_state.actual_sequence.each do |date, hash| %>
    <tr>
      <td><%= date %></td>
      <td><%= hash[:aaa_bal].round(2) %></td>
      <td><%= hash[:aaa_pri].round(2) %></td>
      <td><%= hash[:day_int].round(2) %></td>
      <td><%= hash[:tot_int].round(2) %></td>
      <td><%= hash[:tot_chg].round(2) %></td>
      <td><%= hash[:int_chg].round(2) %></td>
      <td><%= hash[:pri_chg].round(2) %></td>
      <td><%= hash[:tot_ipd].round(2) %></td>
      <td><%= hash[:tot_ppd].round(2) %></td>
      <td><%= hash[:tot_bpd].round(2) %></td>
      <td><%= hash[:zzz_int].round(2) %></td>
      <td><%= hash[:zzz_pri].round(2) %></td>
      <td><%= hash[:zzz_bal].round(2) %></td>
      </td>
    </tr>
  <% end %>
</table>